#!/bin/bash
#
# @brief  Set environment for blocko.
#
# @author   Yun Woo Park

blocko_home='~/work/blocko'

# shortcut for 'blocko' working directory
alias blocko='fn_go_initenv $blocko_home'

# shortcut for 'projects'
alias oec='fn_go_initenv $blocko_home/projects/oec'
alias bbr='fn_go_initenv $blocko_home/projects/bbr'
alias mini='fn_go_initenv $blocko_home/projects/fabric_minions'
