#!/bin/bash
#
# @brief  Set environment for blocko.
#
# @author   Yun Woo Park

BLOCKO_HOME=~/work/blocko

# shortcut for 'blocko' working directory
alias blocko='fn_go_initenv $BLOCKO_HOME'

# shortcut for 'projects'
alias oec='fn_go_initenv $BLOCKO_HOME/projects/oec'
alias bbr='fn_go_initenv $BLOCKO_HOME/projects/bbr'
alias mini='fn_go_initenv $BLOCKO_HOME/projects/fabric_minions'
