#!/bin/bash
#
# @brief  Set personal environment for prompt.
#
# @author   Yun Woo Park

#
# export PROMPT_COLOR1 as you wish
# 29-white, 30-black, 31-red, 32-green, 33-yellow, 34-pupple, 35-pink, 36-sky
#
function fn_fancy_prompt ()
{
	export PROMPT_COLOR1=${PROMPT_COLOR1:-33}
	export PROMPT_COLOR2=${PROMPT_COLOR2:-34}

	case "$TERM" in
		xterm-*color) 
			PS1='\[\033[01;${PROMPT_COLOR1}m\]\u@\h\[\033[00m\]:\[\033[01;${PROMPT_COLOR2}m\]\w\$ \[\033[00m\]'
			;;  
		screen-*color)
			PS1='\[\033[01;${PROMPT_COLOR1}m\]\u@\h\[\033[00m\]:\[\033[01;${PROMPT_COLOR2}m\]\w\$ \[\033[00m\]'
			;;  
		*)  
			PS1='\u@\h:\w\$ '
			;;  
	esac
}

#
# export PROMPT_COLOR1 as you wish
# 29-white, 30-black, 31-red, 32-green, 33-yellow, 34-pupple, 35-pink, 36-sky
#
function fn_time_prompt ()
{
	export PROMPT_COLOR1=${PROMPT_COLOR1:-33}
	export PROMPT_COLOR2=${PROMPT_COLOR2:-34}

	case "$TERM" in
		xterm-color) 
			PS1='\[\033[01;${PROMPT_COLOR1}m\]\u@ \D{%m/%d %R}\[\033[00m\] \[\033[01;${PROMPT_COLOR2}m\]\w\$ \[\033[00m\]'
			;;  
		*)  
			PS1='\u@\h:\w\$ '
			;;  
	esac
}

#
# export PROMPT_COLOR1 as you wish
# 29-white, 30-black, 31-red, 32-green, 33-yellow, 34-pupple, 35-pink, 36-sky
#
function fn_custom_prompt ()
{
	export PROMPT_COLOR1=${PROMPT_COLOR1:-33}
	export PROMPT_COLOR2=${PROMPT_COLOR2:-34}
	export PROMPT_COLOR3=${PROMPT_COLOR3:-31}

	if [ -z "$1" ]; then
		fn_time_prompt; return
	fi

	custom_info=$1

	case "$TERM" in
		xterm-color) 
			PS1='\[\033[01;${PROMPT_COLOR1}m\]\u@\h\[\033[00m\] \[\033[01;${PROMPT_COLOR3}m\][$custom_info]\[\033[00m\] \[\033[01;${PROMPT_COLOR2}m\]\w\$ \[\033[00m\]'
			;;  
		*)  
			PS1='\u@\h:\w\$ '
			;;  
	esac
}
