#!/bin/sh

# netcheck shortcut
alias netcheck="lsof -i -P | grep -i listen"

# vim
alias vim="vi"

# gitk
alias gitk="gitk --all"

# crudini
# https://github.com/pixelb/crudini
export CRUDINI_HOME=${YP_WORK}/bin/crudini-0.9.3
export CRUDINI_PATH=${CRUDINI_HOME}
export PATH=$PATH:$CRUDINI_PATH

# for GIT
alias ga="git add -p"

# for Golang
export GOPATH=${YP_WORK}/go
alias gopath="cd ${GOPATH}/src"

# check shell
export WHICH_SH=`ps -p $$ -o command=`
if [ "${WHICH_SH}" = "-zsh" ];
then
	export SHELL=/bin/zsh
	echo "You are using ZSH"
elif [ "${WHICH_SH}" = "-bash" ];
then
	echo "You are using BASH"
fi

